# # Name of the workflow
# name: Workflow-name

# # Based on what event does the workflow gets triggered? - Events can be push, pull_request, fork etc. https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
# on: 
#   push:
#     branches:
#       # - main
#       - dev

# jobs: # There are many ops you can perform in a job - https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does

#   simpleJob: # Name of the job.
#   name: Simple - Job # This gets displayed on the left hand side of GHA Summary.
#   runs-on: ubuntu-latest # The type of machine on which the workflow runs on. Can be ubuntu-latest, windows-latest, macos-latest etc. https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on