name: Approval Gates Based Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  echo-job-1:
    name: Echo Random Statement - 1
    runs-on: ubuntu-latest
    outputs:
      var: ${{ steps.st_1.outputs.var }}
    steps:
      - name: Echo Statement - 1
        id: st_1
        run: |
          echo 'This is statement - 1'
          echo 'var=hello_from_job_1' >> $GITHUB_OUTPUT

  echo-job-2:
    name: Echo Random Statement - 2
    runs-on: ubuntu-latest
    environment:
        echo
        
    steps:
      - name: Echo Previous Job Statement
        run: echo '${{ needs.echo-job-1.outputs.var }}'
