name: Echo on Ubuntu

on: [push]

jobs:
    echo-on-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Echo on Ubuntu
              run: echo "This is the first statement on Ubuntu"