# Problem Statement: Create a workflow that runs a specific job every Monday at 8 AM UTC.
# The job should check out the repository, run a script that generates a weekly report, and then commit and push the report to a specific branch.

name: Scheduled Event Workflow

on:
  schedule:
    - cron: "03 7 * * *"

permissions: 
  contents: write

jobs:
  run-weekly-report:
    name: Run Weekly Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install Dependencies
        working-directory: Scripts
        run: pip install -r requirements.txt
      
      - name: Execute Script
        working-directory: Scripts
        run: python weekly_report.py

      - name: Get Today's Date
        run: echo "todays_date=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: Push & Commit
        uses: github-actions-x/commit@v2.9
        with:
            files: Scripts/sales_report.csv
            commit-message: Weekly Report Updated for ${{ env.todays_date }}
            github-token: ${{ secrets.GITHUB_TOKEN }}
            push-branch: weekly_sales_report
            name: Reporter
