name: "Terraform Deploy - Azure Resources"

on:
  pull_request:
    branches:
        - main
  push:
    branches:
        - main

permissions:
  contents: read
  issues: write

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    environment: development

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - uses: azure/login@v2
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false

  terraform-apply:
    if: github.branch == main
    needs: terraform-plan
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    environment: development

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - uses: azure/login@v2
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}        

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Seek Approval
        uses: trstringer/manual-approval@v1
        with:
            secret: ${{ github.TOKEN }}
            approvers: Rahul-0312
            minimum-approvals: 1
            issue-title: "${{ github.actor }} is seeking TF Apply Approval"
            issue-body: "Please can you approve or deny the deployment the TF resources."

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
